"use client";

import { BookOpen, CarFront, ChevronRight, CircleParking, Languages, Menu, Phone, Play, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const youtubeUrl = "https://www.youtube.com/@drive4pro4tv";
const schoolUrl = "https://teens.texasdrivereducation.info";

const learningTopics = [
  ["Parallel parking", "Build a calm, repeatable approach to positioning, mirrors, and control.", CircleParking],
  ["Road-ready habits", "Review observation, lane changes, turns, signs, and safe decision-making.", ShieldCheck],
  ["Confidence behind the wheel", "Explore practical topics that support first-time and returning drivers.", CarFront],
];

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const closeMenu = () => setMobileOpen(false);

  return (
    <main className="min-h-screen overflow-hidden bg-[#fffdf5] text-[#1a1a1a]">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-[#231f20]/10 bg-[#fffdf5]/95 backdrop-blur-xl">
        <div className="mx-auto flex h-[76px] max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-14">
          <a href="#top" className="flex items-center" aria-label="Drive4Pro4TV home"><img src="/drive4pro-logo.jpeg" alt="Drive4Pro4TV" className="h-10 w-[190px] object-cover object-[center_42%] sm:h-12 sm:w-[228px]" /></a>
          <nav className="hidden items-center gap-8 text-sm font-bold lg:flex" aria-label="Primary navigation"><a className="nav-link" href="#learn">Learn</a><a className="nav-link" href="#watch">Watch</a><a className="nav-link" href="#fontaine">Fontaine Driving School</a></nav>
          <Button asChild className="hidden h-11 rounded-full bg-[#d8192d] px-5 font-bold text-white hover:bg-[#b81224] lg:flex"><a href={youtubeUrl} target="_blank" rel="noopener noreferrer"><Play className="mr-2 size-4 fill-current" />Watch on YouTube</a></Button>
          <button className="grid size-11 place-items-center rounded-full border border-black/10 lg:hidden" aria-label={mobileOpen ? "Close menu" : "Open menu"} onClick={() => setMobileOpen((value) => !value)}>{mobileOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button>
        </div>
        {mobileOpen && <div className="border-t border-black/5 bg-[#fffdf5] px-5 py-5 lg:hidden"><nav className="grid gap-1 text-base font-bold"><a className="rounded-xl px-3 py-3 hover:bg-[#fff3a6]" href="#learn" onClick={closeMenu}>Learn</a><a className="rounded-xl px-3 py-3 hover:bg-[#fff3a6]" href="#watch" onClick={closeMenu}>Watch</a><a className="rounded-xl px-3 py-3 hover:bg-[#fff3a6]" href="#fontaine" onClick={closeMenu}>Fontaine Driving School</a><a className="mt-2 rounded-xl bg-[#d8192d] px-3 py-3 text-white" href={youtubeUrl} target="_blank" rel="noopener noreferrer">Watch on YouTube</a></nav></div>}
      </header>

      <section id="top" className="relative overflow-hidden bg-[#ffe300] pb-16 pt-[126px] sm:pb-20 sm:pt-[150px] lg:pb-24">
        <div className="hero-radiance absolute inset-0" aria-hidden="true" />
        <div className="relative mx-auto grid max-w-[1440px] items-center gap-12 px-5 sm:px-8 lg:grid-cols-[1.06fr_.94fr] lg:px-14">
          <div className="max-w-[760px]"><p className="mb-6 inline-flex rounded-full border border-[#231f20]/20 bg-white/65 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-[#a50f20]">Drive4Pro4TV learning hub</p><h1 className="font-display text-[clamp(3.5rem,7vw,7.7rem)] font-black leading-[.86] tracking-[-.07em] text-[#231f20]">Learn the road.<br /><span className="text-[#d8192d]">Watch the moves.</span></h1><p className="mt-8 max-w-2xl text-lg font-medium leading-8 text-[#3b3435] sm:text-xl">Helpful driving videos for Fontaine Driving School students, families, and anyone building stronger everyday driving habits.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-14 rounded-full bg-[#d8192d] px-8 text-base font-bold text-white shadow-[0_14px_32px_rgba(216,25,45,.24)] hover:bg-[#b81224]"><a href={youtubeUrl} target="_blank" rel="noopener noreferrer"><Play className="mr-2 size-5 fill-current" />Explore the YouTube channel</a></Button><Button asChild variant="outline" size="lg" className="h-14 rounded-full border-[#231f20]/20 bg-white/75 px-8 text-base font-bold text-[#231f20] hover:bg-white"><a href="#learn">See learning topics</a></Button></div><p className="mt-6 max-w-xl text-sm leading-6 text-[#4b4142]">Drive4Pro4TV is a video-learning companion for Fontaine Driving School. Enrollment, scheduling, and school services are handled directly by Fontaine Driving School.</p></div>
          <div className="relative mx-auto w-full max-w-[580px]"><div className="relative overflow-hidden rounded-[2rem] bg-[#211f20] p-7 text-white shadow-[0_34px_70px_rgba(86,68,0,.28)] sm:p-10"><div className="absolute -right-28 -top-24 size-72 rounded-full bg-[#d8192d] opacity-95" /><div className="absolute -bottom-24 -left-24 size-64 rounded-full border-[28px] border-[#ffe300]" /><div className="relative"><div className="flex items-center justify-between"><span className="rounded-full bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[0.15em]">Video-first learning</span><Play className="size-8 fill-white" /></div><div className="mt-20 sm:mt-28"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#ffe300]">Start with a skill</p><h2 className="mt-3 max-w-md text-4xl font-black leading-[.95] tracking-[-.05em] sm:text-5xl">See it. Understand it. Practice it.</h2></div><a href={youtubeUrl} target="_blank" rel="noopener noreferrer" className="mt-10 flex items-center justify-between rounded-[1.4rem] border border-white/15 bg-white/10 p-5 font-bold backdrop-blur transition hover:bg-white/15"><span className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#d8192d]"><Play className="size-4 fill-current" /></span>Drive4Pro4TV on YouTube</span><ChevronRight className="size-5" /></a></div></div><div className="absolute -bottom-6 -left-3 hidden max-w-[235px] rounded-2xl border border-black/10 bg-white p-4 shadow-xl sm:block"><p className="text-xs font-black uppercase tracking-[.14em] text-[#d8192d]">For Fontaine students</p><p className="mt-2 text-sm font-bold leading-5">A helpful place to revisit the skills you are working on.</p></div></div>
        </div>
      </section>

      <section id="learn" className="bg-[#fffdf5] py-24 sm:py-32"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-14"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="section-kicker">Learn at your pace</p><h2 className="section-title mt-4">Helpful videos for the moments drivers practice most.</h2></div><p className="max-w-2xl text-lg leading-8 text-zinc-600 lg:justify-self-end">Use the channel as a study companion before, between, or after your driving-school lessons. These videos support learning; they do not replace instruction from your school.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{learningTopics.map(([title, copy, Icon], index) => <article key={title as string} className={`topic-card ${index === 1 ? "topic-card-red" : ""}`}><span className="grid size-14 place-items-center rounded-2xl bg-current/[.08]"><Icon className="size-7" /></span><h3 className="mt-16 text-3xl font-black tracking-[-.04em]">{title}</h3><p className="mt-4 max-w-sm text-base leading-7 opacity-70">{copy}</p><a href={youtubeUrl} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 text-sm font-black">Find videos <ChevronRight className="size-4" /></a></article>)}</div></div></section>

      <section id="watch" className="bg-[#211f20] py-24 text-white sm:py-32"><div className="mx-auto grid max-w-[1440px] items-center gap-12 px-5 sm:px-8 lg:grid-cols-[1fr_.88fr] lg:px-14"><div><p className="section-kicker text-[#ffe300]">Watch with purpose</p><h2 className="section-title mt-4 text-white">Keep the learning going after class.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">From first-time drivers to adults refreshing their skills, Drive4Pro4TV makes it easy to revisit common driving topics and arrive more prepared for your next lesson.</p><Button asChild size="lg" className="mt-9 h-14 rounded-full bg-[#d8192d] px-8 text-base font-bold text-white hover:bg-[#ef3447]"><a href={youtubeUrl} target="_blank" rel="noopener noreferrer"><Play className="mr-2 size-5 fill-current" />Open Drive4Pro4TV on YouTube</a></Button></div><div className="rounded-[2rem] border border-white/10 bg-white/[.06] p-7 sm:p-9"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-[#d8192d]"><Play className="size-7 fill-current" /></span><div><p className="font-black">A channel built for learners</p><p className="mt-1 text-sm text-white/55">Watch before you practice.</p></div></div><div className="mt-9 grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2">{["First-time drivers", "Adult learners", "Parking practice", "Defensive habits"].map((item) => <div key={item} className="bg-[#292627] px-5 py-6 text-sm font-bold text-white/85">{item}</div>)}</div></div></div></section>

      <section id="fontaine" className="bg-[#fff5a5] py-24 sm:py-32"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 sm:px-8 lg:grid-cols-[.84fr_1.16fr] lg:px-14"><div><p className="section-kicker">About the school</p><h2 className="section-title mt-4">Fontaine Driving School.</h2><p className="mt-7 max-w-lg text-lg leading-8 text-[#443a30]">Fontaine Driving School is the school connected with these learning resources. For school classes, registration, schedules, and official services, please contact Fontaine directly.</p><div className="mt-8 grid gap-3"><a className="contact-link" href="tel:+12817937804"><Phone className="size-5 text-[#d8192d]" />281-793-7804</a><a className="contact-link" href="tel:+12817487964"><Phone className="size-5 text-[#d8192d]" />281-748-7964</a><p className="flex gap-3 px-1 text-base leading-7 text-[#443a30]"><span className="font-black text-[#d8192d]">Address</span><span>9859 S. Kirkwood Rd<br />Houston, TX 77099</span></p></div><Button asChild variant="outline" size="lg" className="mt-8 h-13 rounded-full border-[#231f20]/20 bg-white px-7 font-bold text-[#231f20] hover:bg-white"><a href={schoolUrl} target="_blank" rel="noopener noreferrer"><Languages className="mr-2 size-5" />Online school classes</a></Button></div><div className="grid gap-5 sm:grid-cols-2"><figure className="overflow-hidden rounded-[1.5rem] border border-[#231f20]/10 bg-white shadow-[0_18px_42px_rgba(103,83,0,.12)]"><img src="/fontaine-card-front.jpg" alt="Fontaine Driving School contact card" className="aspect-[3/4] h-full w-full object-cover object-center" /></figure><figure className="overflow-hidden rounded-[1.5rem] border border-[#231f20]/10 bg-white shadow-[0_18px_42px_rgba(103,83,0,.12)]"><img src="/fontaine-card-services.jpg" alt="Fontaine Driving School services card" className="aspect-[3/4] h-full w-full object-cover object-center" /></figure></div></div></section>

      <footer className="bg-[#151314] py-10 text-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-6 px-5 sm:px-8 md:flex-row md:items-center md:justify-between lg:px-14"><div><p className="text-xl font-black italic">Drive<span className="text-[#d8192d]">4</span>Pro<span className="text-[#d8192d]">4TV</span></p><p className="mt-1 text-xs uppercase tracking-[0.18em] text-white/45">Video learning companion for Fontaine Driving School</p></div><div className="flex flex-wrap gap-5"><a href={youtubeUrl} target="_blank" rel="noopener noreferrer" className="footer-link"><Play className="size-4 fill-current" />YouTube</a><a href={schoolUrl} target="_blank" rel="noopener noreferrer" className="footer-link"><BookOpen className="size-4" />Online classes</a></div></div></footer>
    </main>
  );
}
